model_class: 'TFT'

tft_config:
  input_chunk_length: 24
  output_chunk_length: 12
  hidden_size: 32
  lstm_layers: 2
  batch_size: 16
  n_epochs: 5
  dropout: 0.1
  use_static_covariates: false
  add_relative_index: false
  # optimizer_kwargs:
    # lr: 1e-3
  random_state: 42
  save_checkpoints: true
  torch_kwargs:  # custom loss
    loss_fn: "CustomLoss" # MSE