model_class: 'TFT'

weather_forecast_features: ['wind_speed_10m', 'grad_accum_ground_0m', 'pres_instant_ground_0m', 't_instant_ground_2m']
weather_actuals_features: ['wind_speed', 'global_radiation', 'air_pressure', 'air_temperature']

tft_config:
  input_chunk_length: 24
  output_chunk_length: 12
  hidden_size: 32
  lstm_layers: 2
  batch_size: 16
  n_epochs: 5
  dropout: 0.1
  use_static_covariates: false
  add_relative_index: false
  # optimizer_kwargs:
    # lr: 1e-3
  random_state: 42
  save_checkpoints: true
  torch_kwargs:  # injecting custom loss
    loss_fn: "CustomLoss" # else MSE or similar metrics