weather_forecast_features: [ 'wind_speed_10m', 'grad_accum_ground_0m', 'pres_instant_ground_0m', 't_instant_ground_2m', 'r_instant_ground_2m' ]
weather_actuals_features: [ 'wind_speed', 'global_radiation', 'air_pressure', 'air_temperature', 'relative_humidity' ]

model_class: 'TFT'
run_with_validation: true
gpu_enable: true
trials: 100
num_workers: 8
run_learning_rate_finder: false

tft_config:
  input_chunk_length:
    start: 672 # 7*24*4 (one week)
    end: 672
    increment: 0
  output_chunk_length: 96 #1*24 (one day)
  hidden_size:
    start: 30
    end: 60
    increment: 15
  hidden_continuous_size:
    start: 30
    end: 60
    increment: 15
  num_attention_heads:
    start: 8
    end: 16
    increment: 8
  lstm_layers:
    start: 8
    end: 8
    increment: 0
  batch_size:
    start: 64
    end: 128
    increment: 64
  n_epochs: 20
  dropout:
    start: 0.5
    end: 0.9
    increment: 0.2
  use_static_covariates: [ true ]
  add_relative_index: [ false ]
  optimizer_kwargs:
    lr: 0.001
  #  random_state: 42
  #  save_checkpoints: true
  loss_fn: "MSE" # Custom or MSE or similar metrics

