weather_forecast_features: [ 'wind_speed_10m', 'grad_accum_ground_0m', 'pres_instant_ground_0m', 't_instant_ground_2m', 'r_instant_ground_2m' ]
weather_actuals_features: [ 'wind_speed', 'global_radiation', 'air_pressure', 'air_temperature', 'relative_humidity' ]

model_class: 'TFT'
run_with_validation: true
gpu_enable: true
run_learning_rate_finder: false

# from "Application of Temporal Fusion Transformer for Day-Ahead PV Power Forecasting"
tft_config:
  input_chunk_length: 672 # 7*24*4
  output_chunk_length: 96 #1*24
  hidden_size: 45
  hidden_continuous_size: 45
  num_attention_heads: 16
  lstm_layers: 4
  batch_size: 128
  n_epochs: 200
  dropout: 0.5
  use_static_covariates: true
  add_relative_index: false
  optimizer_kwargs:
    lr: 0.001
  random_state: 42
  save_checkpoints: true
  loss_fn: "Custom" # else MSE or similar metrics
